version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      #- $(aws ecr get-login --region ap-south-1 --no-include-email)
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 381491848779.dkr.ecr.us-east-2.amazonaws.com
      # Replace with this to your repository URI
      - REPOSITORY_URI=381491848779.dkr.ecr.us-east-2.amazonaws.com/demo-r-s3
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo building the tar file
      - ls
      - chmod +x go.sh
      - ./go.sh
      - echo loading the Docker image...
      - docker load < demo-r-ecs.tar.gz
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to repo
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - aws ecs update-service --cluster demo-cluster --service demo-r-s3-service --region us-east-2 --force-new-deployment
      
